Mise à jour du Makefile

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -2,7 +2,7 @@ CC = g++
 CFLAGS = -Wall -Wextra
 OUTPUT = main
 
-$(OUTPUT): main.cpp lib/reader.hpp lib/maze.hpp lib/cell.hpp lib/wall.hpp
+$(OUTPUT): main.cpp lib/reader.o lib/maze.o lib/cell.o lib/wall.o
 	@echo "Compiling..."
 	@$(CC) $(CFLAGS) $^ -o $(OUTPUT)
 	@echo "Done."
@@ -15,13 +15,15 @@ cell.o: lib/cell.cpp lib/cell.hpp lib/wall.hpp
 
 wall.o: lib/wall.cpp lib/wall.hpp
 
-
-
-run_cmd =./$(OUTPUT) $(1); \
-	EXIT_CODE=$$?; \
-    echo "Exit code: $$EXIT_CODE"; \
+run_output =echo "Running:./$(OUTPUT) $(1)"; \
+  ./$(OUTPUT) $(1); \
+    EXIT_CODE=$$?; \
     if [ $$EXIT_CODE -ne 0 ]; then \
-        echo "    Error: $(OUTPUT) returned non-zero exit code $$EXIT_CODE"; \
+        echo -e "\033[31mExit code: $$EXIT_CODE\033[0m"; \
+        echo -e "\033[31mError: $(OUTPUT) returned non-zero exit code $$EXIT_CODE\033[0m"; \
+    else \
+        echo -e "\033[32mExit code: $$EXIT_CODE\033[0m"; \
+        echo -e "\033[32mSuccess: $(OUTPUT) returned zero exit code\033[0m"; \
     fi
 
 .PHONY: clean run
@@ -32,6 +34,11 @@ clean:
 
 run: $(OUTPUT)
 	@echo "Running..."
-	@$(call run_cmd, "")
-	@$(call run_cmd, "Makefile")
+	@echo "--------------------------------"
+	@$(call run_output, "")
+	@echo "--------------------------------"
+	@$(call run_output, "test")
+	@echo "--------------------------------"
+	@$(call run_output, "Makefile")
+	@echo "--------------------------------"
 	@echo "Done."
