Ajout de la prise d'argument dans le main et mise à jour du Makefile pour réaliser plusieurs tests

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -15,8 +15,23 @@ cell.o: lib/cell.cpp lib/cell.hpp lib/wall.hpp
 
 wall.o: lib/wall.cpp lib/wall.hpp
 
-.PHONY: clean
+
+
+run_cmd =./$(OUTPUT) $(1); \
+	EXIT_CODE=$$?; \
+    echo "Exit code: $$EXIT_CODE"; \
+    if [ $$EXIT_CODE -ne 0 ]; then \
+        echo "    Error: $(OUTPUT) returned non-zero exit code $$EXIT_CODE"; \
+    fi
+
+.PHONY: clean run
 clean:
 	@echo "Cleaning up..."
 	@rm -f $(OUTPUT) */*.o
+	@echo "Done."
+
+run: $(OUTPUT)
+	@echo "Running..."
+	@$(call run_cmd, "")
+	@$(call run_cmd, "Makefile")
 	@echo "Done."
